// Play headlines: a long feed sentence becomes a few words.
import assert from 'node:assert/strict';
import { shortPlay as sp } from '../js/moments.js';
const eq = (league, text, want, p) => assert.equal(sp(league, text, p), want, text);
eq('nfl', '(Shotgun) D.Jones pass short right to S.McGowan to WAS 45 for 7 yards (Q.Martin).', '7-yd catch');
eq('nfl', 'T.Way punts 34 yards to IND 20, Center-T.Ott, fair catch by J.Downs.', '34-yd punt');
eq('nfl', 'D.Stevens 29 yard field goal is GOOD, Center-T.Ott, Holder-T.Way.', '29-yd FG');
eq('nfl', 'M.Glass 52 yard field goal is No Good, Wide Right.', 'Missed 52-yd FG');
eq('nfl', '(Shotgun) M.Mariota sacked at WAS 30 for -6 yards (A.Adebawore).', '6-yd sack');
eq('nfl', 'J.Taylor left tackle to IND 42 for 4 yards (B.Wagner).', '4-yd run');
eq('nfl', '(Shotgun) D.Jones pass incomplete deep left to A.Pierce.', 'Incomplete pass');
eq('nfl', 'J.Daniels pass deep middle to T.McLaurin for 38 yards, TOUCHDOWN.', '38-yd TD catch');
eq('nfl', 'B.Robinson up the middle for 2 yards, TOUCHDOWN.', '2-yd TD run');
eq('nfl', 'D.Jones pass short middle intended for J.Downs INTERCEPTED by M.Sainristil at WAS 12.', 'Interception');
eq('nfl', 'M.Glass extra point is GOOD, Center-T.Ott.', 'Extra point');
eq('nfl', 'Some odd thing', 'Run', { type: { text: 'Rush' } });
eq('nfl', 'whatever happened here', '12-yd catch', { type: { text: 'Pass Reception' }, statYardage: 12 });
eq('nba', 'Nikola Jokic makes 25-foot three point jumper (Jamal Murray assists)', '25-ft three');
eq('nba', 'Shai Gilgeous-Alexander makes driving dunk', 'Driving dunk');
eq('nba', 'Jaylen Brown misses 12-foot pullup jump shot', 'Missed 12-ft pullup jumper');
eq('nba', 'Jayson Tatum makes free throw 1 of 2', 'Free throw');
eq('nba', 'Chet Holmgren defensive rebound', 'Rebound');
eq('nba', 'Luka Doncic bad pass (Jalen Williams steals)', 'Steal');
eq('mlb', 'Judge homered to left (410 feet), Soto scored.', '410-ft home run');
eq('mlb', 'Devers struck out swinging.', 'Strikeout');
eq('mlb', 'Diaz doubled to deep right, Arozarena scored.', 'Double');
eq('mlb', 'Volpe grounded out to shortstop.', 'Groundout');
eq('mlb', 'Soto walked.', 'Walk');
console.log('ok - play headlines');
